Repository semi-project-team/PSMC, pull requests merged in 2024-05, with the labels that each got.

#51 loginpage 중간정검
  DB/DA#/Psmc db erd.damx
  project/PSMC/build.gradle
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/MainController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/AuthDetails.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/service/AuthService.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/UserRole.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/EmployeeDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/configuration/MybatisConfig.java
  project/PSMC/src/main/java/com/javaclass/psmc/configuration/SecurityConfig.java
  project/PSMC/src/main/java/com/javaclass/psmc/configuration/handler/AuthFailHandler.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/controller/RegisterController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/controller/UserController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dto/MemberRegistDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dto/SignUpDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/application.properties
  project/PSMC/src/main/resources/application.yml
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/registerReq.css
  project/PSMC/src/main/resources/templates/auth/fail.html
  project/PSMC/src/main/resources/templates/main.html
  project/PSMC/src/main/resources/templates/registerReq/registerReq.html
  project/PSMC/src/main/resources/templates/registerReq/takeCode.html
  project/PSMC/src/main/resources/templates/registerReq/term.html
Labels: 🔨Refactor, 🔧Setting

#70 main 페이지 완성
  HTML/common/img/about-us-16-64 (1).png
  HTML/main/main.css
  HTML/main/main.html
Labels: 🎨Html&css

#77 메인 인텔리졔에 옮김
  HTML/main/main.js
  project/.idea/.gitignore
  project/.idea/compiler.xml
  project/.idea/gradle.xml
  project/.idea/jarRepositories.xml
  project/.idea/misc.xml
  project/.idea/modules.xml
  project/.idea/project.iml
  project/.idea/vcs.xml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: 🎨Html&css

#78 css link 추가
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: 🎨Html&css

#79 필요없는 구조 삭제하기
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/ProjectDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/service/projectService.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/ProjectMapper.java
  project/PSMC/src/main/resources/mappers/Project.xml
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/selectPatient/selectPatient.html
Labels: 🔧Setting

#81 메인페이지 + 네비바
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
Labels: 🎨Html&css

#82 auth details 권한 들고 다니기
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/controller/UserController.java
  project/PSMC/src/main/resources/static/assets/css/schedule1.css
  project/PSMC/src/main/resources/static/assets/css/schedule1.scss
  project/PSMC/src/main/resources/static/assets/js/schedulemain.js
  project/PSMC/src/main/resources/templates/medical/schedule.html
Labels: ✨Feature

#85 header 추가
  project/PSMC/src/main/resources/static/assets/css/header.css
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: 🎨Html&css

#93 nav완성
  HTML/nav/nav.css
  HTML/nav/nav.html
  HTML/nav/nav.js
  project/.idea/compiler.xml
  project/PSMC/src/main/resources/static/assets/css/nav.css
  project/PSMC/src/main/resources/static/assets/js/nav.js
  project/PSMC/src/main/resources/templates/common/nav.html
Labels: 🎨Html&css

#96 schedule doc 부분 완료
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/nav.js
  project/PSMC/src/main/resources/static/assets/js/schedule.js
  project/PSMC/src/main/resources/templates/common/nav.html
Labels: ✨Feature

#103 scheduler 완성
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllMediDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllTheraDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/schedule.js
  project/PSMC/src/main/resources/templates/schedule/scheduler.html
Labels: ✨Feature

#105 mediConnect 게시판 html css
  HTML/mediConnect/mediConnect.css
  HTML/mediConnect/mediConnect.html
  HTML/mediConnectWrite/mediConnectWrite.css
  HTML/mediConnectWrite/mediConnectWrite.html
Labels: 🎨Html&css

#108 css/mypage2
  HTML/mypage/mypage.css
  HTML/mypage/mypage.html
  image/비밀번호변경.png
  image/프로필.png
  image/회원정보수정.png
Labels: 🎨Html&css

#110 css mypage 인텔리졔에 올림
  HTML/mypage/mypage.html
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/assets/js/mypage.js
  project/PSMC/src/main/resources/static/common/img/비밀번호변경.png
  project/PSMC/src/main/resources/static/common/img/프로필.png
  project/PSMC/src/main/resources/static/common/img/회원정보수정.png
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/mypage/mypage.html
Labels: 🎨Html&css

#115 mediConnect 프로젝트 조회기능 수정, 게시글 전체조회기능 만들기
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/ProjectsService.java
  project/PSMC/src/main/resources/mappers/ProjectMapper.xml
  project/PSMC/src/main/resources/templates/doc/mediConnect.html
Labels: ✨Feature, 🎨Html&css

#116 mypage 인텔리졔에 올림
  HTML/main/main.html
  project/.idea/modules/PSMC.main.iml
  project/.idea/modules/PSMC.test.iml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/common/img/change.png
  project/PSMC/src/main/resources/static/common/img/edit.png
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/mypage/mypage.html
Labels: 🎨Html&css

#118 메인페이지 스케쥴 연동
  HTML/main/main.css
  HTML/main/main.html
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/ProjectsDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/TheraProjectDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/templates/auth/login.html
  project/untitled/.idea/gradle.xml
Labels: ✨Feature

#121 main page 식단표 crud 작업
  HTML/main/main.css
  HTML/main/main.html
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/MyPatientDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/method/MakePhoneNumber.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/method/MenuHandling.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllTheraDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AssignToEmpDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/ConnectProjectDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/CreateToEmpDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/MItoProDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/ProfileDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TheraToProDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayMenuDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TtoMIDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dto/LoginUserDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/static/assets/js/schedule.js
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#122 main page doctor 예약 완료
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/ProjectsDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/TheraProjectDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllMediDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllTheraDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#123 메인페이지 예약 기능 제한
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/TheraProjectDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraInfoDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/method/FindTimeCode.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TheraJSONDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayAllMediDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayAllTheraDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#124 메인페이지 와 스케쥴러 예약 및 수정 시간 제한 설정 완료
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/schedule/scheduler.html
Labels: ✨Feature

#130 modal update
  HTML/main/main.css
  HTML/main/main.html
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/MainController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/resources/application.yml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/static/assets/css/schedule.css
  project/PSMC/src/main/resources/static/assets/js/schedule.js
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/member/registerReq.html
  project/PSMC/src/main/resources/templates/schedule/scheduler.html
Labels: ✨Feature

#131 mainpage 약간 또 수정 (폰트)
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
Labels: 🎨Html&css

#132 main page modal input 제한 조건 완수
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#133 mainpage-modal
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#138 메인페이지 mediconnect theralink db column 제외 완료
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#139 마이페이지 수정 + 비밀번호 변경 완성
  change/change.css
  change/change.html
  change/change.js
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ChangeController.java
  project/PSMC/src/main/resources/static/assets/css/change.css
  project/PSMC/src/main/resources/static/assets/css/edit.css
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/assets/js/change.js
  project/PSMC/src/main/resources/templates/mypage/change.html
  project/PSMC/src/main/resources/templates/mypage/edit.html
  project/PSMC/src/main/resources/templates/mypage/mypage.html
Labels: 🎨Html&css

#140 [HTML/CSS] staff 페이지
  HTML/staff/staff.css
  HTML/staff/staff.html
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/StaffController.java
Labels: 🎨Html&css

#141 theralink 시작
  HTML/TheraLink/firstPage.html
  HTML/TheraLink/general.css
  HTML/TheraLink/secondPage.html
  HTML/TheraLink/thirdPage.html
  HTML/header/header.css
  HTML/header/header.html
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: 🎨Html&css

#145 [HTML/CSS] TheraLink html 완성
  HTML/TheraLink/chatting.css
  HTML/TheraLink/firstPage.html
  HTML/TheraLink/fonts/iu.eot
  HTML/TheraLink/fonts/iu.svg
  HTML/TheraLink/fonts/iu.ttf
  HTML/TheraLink/fonts/iu.woff
  HTML/TheraLink/general.css
  HTML/TheraLink/image-uploader.min.css
  HTML/TheraLink/image-uploader.min.js
  HTML/TheraLink/secondPage.css
  HTML/TheraLink/secondPage.html
  HTML/TheraLink/thirdPage.html
  HTML/common/img/plus-in-circle-filled.png
Labels: 🎨Html&css

#149 navbar 수정 !!
  .idea/workspace.xml
  project/PSMC/src/main/resources/static/assets/css/header.css
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/assets/css/nav.css
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/common/header.html
  project/PSMC/src/main/resources/templates/common/nav.html
Labels: 🎨Html&css

#150 nav랑 mypage 위치 약간 변경
  project/PSMC/src/main/resources/static/assets/css/change.css
  project/PSMC/src/main/resources/static/assets/css/edit.css
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/assets/css/nav.css
  project/PSMC/src/main/resources/templates/common/nav.html
Labels: 🎨Html&css

#153 네비 찐막
  project/PSMC/src/main/resources/static/assets/css/nav.css
  project/PSMC/src/main/resources/static/assets/js/nav.js
  project/PSMC/src/main/resources/templates/common/nav.html
Labels: 🎨Html&css

#154 [FEATURE] theraLink 기능
  HTML/TheraLink/firstPage.html
  HTML/TheraLink/general.css
  HTML/TheraLink/secondPage.css
  HTML/TheraLink/secondPage.html
  project/PSMC/build.gradle
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/MyPatientDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraLinkDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkWithMonthDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/application.yml
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/schedule.css
  project/PSMC/src/main/resources/static/assets/css/secondPage.css
  project/PSMC/src/main/resources/static/assets/css/theraFirstPage.css
  project/PSMC/src/main/resources/static/assets/js/firstPage.js
  project/PSMC/src/main/resources/templates/theraLink/firstPage.html
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#155 [HTML/CSS] MediConnect Detail 디자인
  HTML/mediConnectDetail/mediConnectDetail.css
  HTML/mediConnectDetail/mediConnectDetail.html
Labels: 🎨Html&css

#164 [FEATURE]theraLink 이미 있는 채팅 끌어오기 끝
  HTML/TheraLink/secondPage.html
  project/PSMC/.gitignore
  project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraChatDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/MessageDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraChatForBlogDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/application.yml
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/secondPage.css
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#165 [FEATURE]chatting 기능 업데이트
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/MessageDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
Labels: ✨Feature

#167 [BUGFIX]theralink 채팅 기능에 있던 오류 수정
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/header.js
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/templates/common/nav.html
Labels: 🐞BugFix🔧

#170 [FEATURE] theralink 채팅 기능 삭제 완성
  HTML/TheraLink/chatting.css
  HTML/TheraLink/secondPage.html
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/ChatDeleteDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/chatting.css
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#173 [FEATURE]THERALINK 사진 CONTROLLER에 보내기 성공
  HTML/TheraLink/image-uploader.min.js
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/resources/application.yml
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/image-uploader.min.js
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#175 mediconnect css 완성
  project/PSMC/src/main/resources/static/assets/css/change.css
  project/PSMC/src/main/resources/static/assets/css/mediConnect.css
  project/PSMC/src/main/resources/templates/medi/mediConnect.html
Labels: 🎨Html&css

#178 [FEATURE] theralink 사진 업로드
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TheraJSONDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayAllTheraDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/ChatDeleteDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/MessageDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraChatForBlogDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkPhotoDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkWithMonthDTO.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#180 [FEATURE]THERALINK blog 생성및 수정
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/RecieveDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#186 [BUGFIX] theralink 관련 버그 픽스
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/BlogDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/templates/common/nav.html
  project/PSMC/src/main/resources/templates/theraLink/firstPage.html
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: 🐞BugFix🔧

#193 [BUGFIX] theralink 사진관련 오류 수정했습니다
  project/PSMC/src/main/java/com/javaclass/psmc/mypage/controller/EditController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: 🐞BugFix🔧

#198 [FEATURE] profile 이미지 업로드 및 업데이트 완료 했습니다
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/MainController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/EmployeePhotoDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/ProfileDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/assets/js/mypage.js
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/static/common/img/employeeProfile.png
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/main.html
  project/PSMC/src/main/resources/templates/mypage/mypage.html
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#200 [BUGFIX] 아이디 찾기 비밀번호 찾기 모달 창 밖으로 나갈시 데이터가 그대로 남아 있는 부분 해결
  project/PSMC/src/main/resources/static/assets/css/change.css
  project/PSMC/src/main/resources/static/assets/js/main.js
  project/PSMC/src/main/resources/static/common/img/no-image.png
  project/PSMC/src/main/resources/templates/find/findId.html
  project/PSMC/src/main/resources/templates/find/findPassword.html
  project/PSMC/src/main/resources/templates/main.html
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: 🐞BugFix🔧

#203 [feature] edit 완성
  project/PSMC/src/main/resources/templates/mypage/edit.html
Labels: ✨Feature

#206 [Feature] mediConnect d,t 수정 완료, 삭제 기능 오류 수정 완료, 채팅기능 만드는 중
  DB/DA#/Psmc db erd.damx
  HTML/mediConnectDetail/mediConnectDetail.html
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
  project/PSMC/src/main/resources/mappers/ProjectMapper.xml
  project/PSMC/src/main/resources/static/assets/js/mediConnect.js
  project/PSMC/src/main/resources/templates/medi/mediConnect.html
  project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html
Labels: 🐞BugFix🔧, ✨Feature

#208 [FEATURE] JAR 파일에서 프로필 이미지 수정 완료
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/MainController.java
  project/PSMC/src/main/java/com/javaclass/psmc/configuration/ContextConfiguration.java
  project/PSMC/src/main/java/com/javaclass/psmc/configuration/SecurityConfig.java
  project/PSMC/src/main/java/com/javaclass/psmc/configuration/WebConfig.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ChangeController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mypage/controller/EditController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/BlogDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraChatForBlogDTO.java
  project/PSMC/src/main/resources/application.yml
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/static/assets/css/mypage.css
  project/PSMC/src/main/resources/static/assets/js/secondPage.js
  project/PSMC/src/main/resources/static/common/employeeimg/d94958389ca14794aa79b6f6e4959561.jpg
  project/PSMC/src/main/resources/static/common/employeeimg/sdf.txt
  project/PSMC/src/main/resources/static/common/postimg/481056b7638f4904aa2553f1e0ab80ad.jpg
  project/PSMC/src/main/resources/static/common/postimg/5927efd6621d48a385dc737e4a43b99b.png
  project/PSMC/src/main/resources/static/common/postimg/c20ba2c6518a4c379f9a3cd20a5a0e0e.jpg
  project/PSMC/src/main/resources/static/common/postimg/sdf.txt
  project/PSMC/src/main/resources/templates/auth/login.html
  project/PSMC/src/main/resources/templates/medi/mediConnect.html
  project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html
  project/PSMC/src/main/resources/templates/medi/projects.html
  project/PSMC/src/main/resources/templates/mypage/change.html
  project/PSMC/src/main/resources/templates/mypage/edit.html
  project/PSMC/src/main/resources/templates/mypage/mypage.html
  project/PSMC/src/main/resources/templates/schedule/scheduler.html
  project/PSMC/src/main/resources/templates/theraLink/firstPage.html
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: ✨Feature

#212 [feature] 메디커넥트 넣기 1차 완성
  HTML/mediConnect/mediConnect.html
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
  project/PSMC/src/main/resources/mappers/ProjectMapper.xml
  project/PSMC/src/main/resources/static/assets/css/mediConnect.css
  project/PSMC/src/main/resources/templates/medi/mediConnect.html
Labels: 🐞BugFix🔧, ✨Feature

#213 [FEATURE] THERALINK 관련 최근 4개 메인페이지 띄우기 & 검색기능 일부도 받아들일수 있도록 수정
  DB/DA#/Psmc db erd.damx
  project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
  project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/MiniTheraLinkDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
  project/PSMC/src/main/resources/mappers/UserMapper.xml
  project/PSMC/src/main/resources/static/assets/css/mainpage.css
  project/PSMC/src/main/resources/templates/auth/login.html
Labels: ✨Feature

#214 Staff2
  project/PSMC/src/main/java/com/javaclass/psmc/staff/controller/EmployeeController.java
  project/PSMC/src/main/java/com/javaclass/psmc/staff/model/dao/EmployeeMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/staff/model/dto/EmployeeToMedicalFieldDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/staff/model/service/EmployeeService.java
  project/PSMC/src/main/resources/mappers/EmployeeMapper.xml
  project/PSMC/src/main/resources/static/assets/css/list.css
  project/PSMC/src/main/resources/static/assets/css/search.css
  project/PSMC/src/main/resources/templates/staff/list.html
  project/PSMC/src/main/resources/templates/staff/search.html
Labels: ✨Feature, 🎨Html&css

#217 [bugfix] DTO 및 xml 수정
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dto/NewProjectShowDTO.java
  project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/ProjectsService.java
  project/PSMC/src/main/resources/mappers/ProjectMapper.xml
Labels: 🐞BugFix🔧

#218 [refactor]상대경로 수정
  project/PSMC/src/main/java/com/javaclass/psmc/staff/controller/EmployeeController.java
  project/PSMC/src/main/resources/templates/staff/list.html
  project/PSMC/src/main/resources/templates/staff/search.html
Labels: 🔨Refactor

#219 [HTML/CSS]theralink 컨텐츠가 없을때 빈공간 관련 이미지
  project/PSMC/src/main/resources/static/assets/css/secondPage.css
  project/PSMC/src/main/resources/templates/theraLink/firstPage.html
  project/PSMC/src/main/resources/templates/theraLink/secondPage.html
Labels: 🎨Html&css

#223 [BUGFIX] SCHEULER 에서 상대경로 오류 수정
  project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
Labels: 🐞BugFix🔧
